# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-notes' : '@same'
    'pim/akonadi-search' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kmime' : '@same'
    'pim/kontactinterface' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/libkdepim' : '@same'
    'pim/pimcommon' : '@same'
    'pim/grantleetheme' : '@same'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kdnssd': '@latest'
    'frameworks/kglobalaccel': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kitemmodels': '@latest'
    'frameworks/kitemviews': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/knewstuff': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/knotifyconfig': '@latest'
    'frameworks/kparts': '@latest'
    'frameworks/ktextwidgets': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/kdoctools': '@latest'
    'libraries/ktextaddons': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'libraries/ktexttemplate': '@stable'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'third-party/grantlee' : '@stable'
