# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/akonadi-notes' : '@same'
    'kde/pim/akonadi-search' : '@same'
    'kde/pim/kcalutils' : '@same'
    'kde/pim/kmime' : '@same'
    'kde/pim/kontactinterface' : '@same'
    'kde/pim/kpimtextedit' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/pimcommon' : '@same'
    'third-party/grantlee' : '@stable'
    'kde/pim/grantleetheme' : '@same'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kdnssd': '@latest'
    'frameworks/kglobalaccel': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kitemmodels': '@latest'
    'frameworks/kitemviews': '@latest'
    'frameworks/kkcmutils': '@latest'
    'frameworks/knewstuff': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/knotifyconfig': '@latest'
    'frameworks/kparts': '@latest'
    'frameworks/ktextwidgets': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/kdoctools': '@latest'
